// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_VZ2256CmrSnxkDs0TS6sqPYpXqGEVrA',
    appId: '1:982696518823:web:06faae53f8ac964a4a6782',
    messagingSenderId: '982696518823',
    projectId: 'eduai-76660',
    authDomain: 'eduai-76660.firebaseapp.com',
    storageBucket: 'eduai-76660.firebasestorage.app',
    measurementId: 'G-R8Q4TYCKLS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_VZ2256CmrSnxkDs0TS6sqPYpXqGEVrA',
    appId: '1:982696518823:android:06faae53f8ac964a4a6782',
    messagingSenderId: '982696518823',
    projectId: 'eduai-76660',
    storageBucket: 'eduai-76660.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_VZ2256CmrSnxkDs0TS6sqPYpXqGEVrA',
    appId: '1:982696518823:ios:06faae53f8ac964a4a6782',
    messagingSenderId: '982696518823',
    projectId: 'eduai-76660',
    storageBucket: 'eduai-76660.firebasestorage.app',
    iosBundleId: 'com.example.eduaiNotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_VZ2256CmrSnxkDs0TS6sqPYpXqGEVrA',
    appId: '1:982696518823:ios:06faae53f8ac964a4a6782',
    messagingSenderId: '982696518823',
    projectId: 'eduai-76660',
    storageBucket: 'eduai-76660.firebasestorage.app',
    iosBundleId: 'com.example.eduaiNotes',
  );
}
